# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Log-Likelihood of Matrix-Variate Normal Data
#' @description It supposes that the data are independently
#'   sampled from `N(0, Psi, Sigma)`.
#'
#' @param x Array of *r x c x n*.
#' @param Psi Row convariance matrix.
#' @param Sig Column covariance matrix.
#'
#' @noRd
cxx_matNormal_lik <- function(x, Psi, Sig) {
    .Call(`_PLFD_cxx_matNormal_lik`, x, Psi, Sig)
}

cxx_mean <- function(x1, x2, flag) {
    .Call(`_PLFD_cxx_mean`, x1, x2, flag)
}

cxx_prec <- function(x1, x2, flag) {
    .Call(`_PLFD_cxx_prec`, x1, x2, flag)
}

