# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Log-Likelihood of Matrix-Variate Normal Data
#' @description It supposes that the data are independently
#'   sampled from `N(0, Psi, Sigma)`.
#'
#' @param x Array of *r x c x n*.
#' @param Psi Row convariance matrix.
#' @param Sig Column covariance matrix.
#'
#' @return Log-likelihood value.
#' @noRd
NULL

#' @title MLE of Row and Column Covariance Matrices
#'
#' @param x Array.
#' @param maxIter The maximal number of iterations.
#' @param tol Error tolerance.
#'
#' @return `list(logLik, Psi, PsiInv, Sig, SigInv)`.
#' @noRd
NULL

#' @title Center Sample Data
#'
#' @param x1 See [get_suppSet()].
#' @param x2 See [get_suppSet()].
#' @param flag The result returned from [get_suppSet()].
#'
#' @return Array.
#' @noRd
NULL

#' @title Estimate Mean Matrices of Class 1 and 2
#' @description If `flag(i, j)` is `FALSE`, `M1(i, j)` and `M2(i, j)` are
#' estimated within groups respectively; otherwise, they are estimated as
#' the pooled mean value.
#'
#' @param x1 See [get_suppSet()].
#' @param x2 See [get_suppSet()].
#' @param flag The result returned from [get_suppSet()].
#'
#' @return Array with two slices.
#' @noRd
cxx_mean <- function(x1, x2, flag) {
    .Call(`_PLFD_cxx_mean`, x1, x2, flag)
}

#' @title Inverse of the MLE of Row and Column Covariance Matrices
#'
#' @param x1  See [get_suppSet()].
#' @param x2  See [get_suppSet()].
#' @param flag The result returned from [get_suppSet()].
#'
#' @return See the value of [cxx_matNormal_mle()].
#' @noRd
cxx_prec <- function(x1, x2, flag) {
    .Call(`_PLFD_cxx_prec`, x1, x2, flag)
}

